# Generated by Django 3.2.8 on 2021-10-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20211012_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_subtitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post_title',
            field=models.CharField(max_length=100),
        ),
    ]
