# Generated by Django 3.2.8 on 2021-10-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_remove_postmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttags',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postmodel', to='base_app.postmodel'),
        ),
    ]
