# Generated by Django 3.2.8 on 2021-10-12 09:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_postmodel_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
