# Generated by Django 3.2.8 on 2021-10-12 09:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_postmodel_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
